### ISSUE TITLE
Roadmap?

### ISSUE THREAD

**Issue by kylebeggs** [JohannesNE/CardiovascularModels.jl#6]
Hi Johannes,

I have quite a bit of experience with these models and plan to use them further in my thesis. I do have working code for my thesis now, but it is all "manually" building the system of ODEs and solving. This approach using ModelingToolkit.jl is something I've had my eye on, so I'd like to contribute and hopefully this reaches maturity enough for me to start using it. So, do you have a roadmap of features and grand plan of what you'd want this to become? perhaps I should write down features I need and I can just begin working on it? Wanted to get your input on things first.

**Comment by JohsEnevoldsen** [comment]
To be honest I have no grand plan. This is a sub-project of my PhD, and the immediate goal is to create a physiologically relevant model, with a main focus on the arterial pressure waveform. I will then do parameter optimization to fit the some arterial waveforms I've recorded under different conditions, and hopefully find meaningful differences in the parameters depending on the conditions (different mechanical ventilation strategies).

To keep track of all the systems, I decided to make it modular from the beginning. I thought that I might as well share it, in case others are interested.

It would be very interesting to collaborate on this! This project will be my main focus for a couple of months now, but I also have a thesis to hand in this summer :shrug: 

I hope this is not discouraging you from contributing. If this should get more traction than I can manage after my PhD, I will happily hand over the keys :)

**Comment by JohsEnevoldsen** [comment]
But a bit more concretely:

I think it would be cool to have a library of modules that can be composed in flexible ways. e.g. different implementations of arterial systems, cardiac drivers, assist devices, ect. Ideally, these could match implementations from specific publications.

Also, it would be nice to have a number of helper function and plotting recipes for working with the solution.

**Comment by JohsEnevoldsen** [comment]
Oh, and full disclosure: I'm a medical doctor with no formal education in either differential equations or programming. Only curiosity.

**Comment by kylebeggs** [comment]
@JohannesNE Does not discourage from contributing! I was just asking as I don't want to intrude on your vision, if there was one. Some code maintainers are more authoritative. I think it would be worth my time to contribute and like you said, once you move on to other projects you can always hand over the keys!

I am also interested in parameter estimation. I think I can add some more components to get started and then maybe come back to help out with the parameter estimation problem.

I think it is advantageous you are a medical doctor as you have access to data to help with the parameter estimation problem. Getting good data has been a problem for me (I am also working on segmenting images to then use in 3D simulations). Impressive that you also have this much knowledge of differential equations and coding. I'll look for a gap and just get started!

**Comment by kylebeggs** [comment]
closing because it was not a real issue

**Comment by JohsEnevoldsen** [comment]
I made a new issue with an overview of how I'm currently trying to structure components.
https://github.com/JohannesNE/CardiovascularModels.jl/issues/7
